create Not Found page
npmStart0/client pull request #27
Opened 2024-12-02 17:46 UTC by 100michal100

create Not Found page #26

2024-12-02 18:55 UTC, RutiRozenberg requested changes
Hi @100michal100 

Great job on the code! I appreciate your effort in implementing the feature. I have some improvements based on our project conventions:

1. Use colors from a 'Theme' object.
2. Use 'variant' for typography size instead of setting height and width.
3. Each definition should be written on a separate line.
4. Navigate with 'useNavigate' from React Router.

Please let me know if you have any questions or need further clarification on these points.

2024-12-04 08:16 UTC, RutiRozenberg requested changes
Please restore the font definition that was removed.

2025-01-13 13:19 UTC, RutiRozenberg requested changes
- Resolve conflicts
- Attach a screenshot of the final result.

2025-01-22 11:14 UTC, RutiRozenberg requested changes
LGTM! 
Upload a screenshot of the final result.

2025-01-22 18:29 UTC, 100michal100 commented
![image](https://github.com/user-attachments/assets/6e02d994-5c6c-40e1-84fa-f8f68e11ff18)

2025-01-23 10:11 UTC, RutiRozenberg requested changes
- Change the size of the words: "הדף לא נמצא" to a larger size.
- Add space above the icon.
- Change the color and shape of the button.

2025-01-26 14:44 UTC, DvoraShechter1 reviewed
LGTM!
@100michal100 - Your code is great!
@RutiRozenberg - Your review is really professional!

2025-01-26 15:08 UTC, RutiRozenberg approved these changes

2025-01-26 15:08 UTC, merged